remving kvm

diff --git a/.github/workflows/android-ci.yml b/.github/workflows/android-ci.yml
--- a/.github/workflows/android-ci.yml
+++ b/.github/workflows/android-ci.yml
@@ -25,13 +25,7 @@ jobs:
           echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
           # Optioneel: probeer het herladen van regels als u een lokale omgeving heeft die dit ondersteunt
           sudo udevadm control --reload-rules || echo "udevadm not found or unable to reload rules"
-          sudo udevadm trigger --name-match=kvm || echo "udevadm not found or unable to trigger rules"
-      - name: Check for KVM device
-        run: |
-          if [ ! -e /dev/kvm ]; then
-            echo "KVM device is not available. Ensure hardware virtualization is enabled.";
-            exit 1;
-          fi        
+          sudo udevadm trigger --name-match=kvm || echo "udevadm not found or unable to trigger rules"      
       - name: Set up JDK 17
         uses: actions/setup-java@v3
         with:
